#############################################################################
# Makefile for building: plasmacoin-client
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  ../plasmacoin-client/plasmacoin-client.pro
# Template: app
# Command: /bin/qmake -o Makefile ../plasmacoin-client/plasmacoin-client.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      	 = Makefile

EQ            	 = =

####### Compiler, tools and options

#
# To use ThreadSanitizer:
# CXXFLAGS - add -fsanitize=thread -fopenmp=libomp
# LFLAGS - add -fsanitize=thread
#

# OS_NAME := $(shell uname -s | tr A-Z a-z)

# os:
# 	@echo $(OS_NAME)

CC            	 = clang
CXX           	 = clang++
GO 			  	 = /usr/bin/go
CRYPTOPP 		 = /usr/src/cryptopp
LIBPLASMACOIN 	 = /usr/lib/plasmacoin
DEFINES       	 = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        	 = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      	 = -pipe -g -std=gnu++17 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
GOFLAGS		  	 = -buildmode c-shared
INCPATH       	 = -I../plasmacoin-client -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-clang -I../.. -I/usr/src -I../../../daemon -I/usr/lib -I/usr/include/boost
QMAKE         	 = /bin/qmake
DEL_FILE      	 = rm -f
CHK_DIR_EXISTS	 = test -d
MKDIR         	 = mkdir -p
COPY          	 = cp -f
COPY_FILE     	 = cp -f
COPY_DIR      	 = cp -f -R
INSTALL_FILE  	 = install -m 644 -p
INSTALL_PROGRAM  = install -m 755 -p
INSTALL_DIR   	 = cp -f -R
QINSTALL      	 = /bin/qmake -install qinstall
QINSTALL_PROGRAM = /bin/qmake -install qinstall -exe
DEL_FILE      	 = rm -f
SYMLINK       	 = ln -f -s
DEL_DIR       	 = rmdir
MOVE          	 = mv -f
TAR           	 = tar -cf
COMPRESS      	 = gzip -9f
DISTNAME      	 = plasmacoin-client-$(VERSION)
DISTDIR 	  	 = ./.tmp/plasmacoin-client-$(VERSION)
HEADER_DIR		 = /usr/include/plasmacoin
LINK          	 = clang++
LFLAGS        	 = -ccc-gcc-name clang++ -L$(LIBPLASMACOIN) -L$(CRYPTOPP)
GOLIBS			 = $(LIBPLASMACOIN)/libpcnetworkd.so
QTLIBS 			 = /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so
SUBLIBS			 =
LIBS          	 = $(QTLIBS) $(GOLIBS) -lGL -lpthread -lcryptopp -lstdc++fs -lboost_system
DAEMON_LIBS   	 = $(GOLIBS) -lplasmacoin -lpthread
AR            	 = ar cqs
RANLIB        	 =
SED           	 = sed
STRIP         	 = strip
VERSION	 	  	 = 0.1.0

####### Output directory

OBJECTS_DIR   	 = ./

####### Files

SOURCES       = ../../transaction.cpp ../../node.cpp ../../block.cpp \
				../../blockchain.cpp ../../receipt.cpp ../../merkle-helpers.cpp ../../rsa-fs.cpp \
				../../dat-fs.cpp ../../transmitter.cpp ../../shared-mem.cpp ../../parse-json.cpp \
				../../validation.cpp ../../hashing.cpp ../../dssize.cpp ../../utility.cpp ../../rsautil.hpp \
				\
				../plasmacoin-client/main.cpp ./plasmacoin-client/mainwindow.cpp moc_mainwindow.cpp \
				../plasmacoin-client/transaction-list.cpp \
				../plasmacoin-client/mining-status.cpp ../plasmacoin-client/moc_mining_status.cpp \
				../plasmacoin-client/recipient-list.cpp ../plasmacoin-client/firebase-auth.cpp \
				moc_firebase_auth.cpp ../plasmacoin-client/account-pages.cpp \
				../plasmacoin-client/transaction-manager.cpp ../plasmacoin-client/connections.cpp \
				\
				../../../netdial/netdial.go ../../../netlisten/netlisten.go \
				../../../netutils/compression.go ../../../netutils/netutils.go ../../../netutils/parser.go \
				../../../handler/handler.go ../../../daemon/pcnetworkd.go ../../../daemon/pcnetworkd.h \
				../../../daemon/daemon.cpp

OBJECTS 	  = main.o \
				transaction.o \
				node.o \
				block.o \
				blockchain.o \
				receipt.o \
				merkle-helpers.o \
				rsa-fs.o \
				dat-fs.o \
				transmitter.o \
				shared-mem.o \
				parse-json.o \
				validation.o \
				hashing.o \
				dssize.o \
				utility.o \
				rsautil.o \
				mainwindow.o \
				moc_mainwindow.o \
				transaction-list.o \
				mining-status.o \
				moc_mining_status.o \
				firebase-auth.o \
				moc_firebase_auth.o \
				account-pages.o \
				address-book.o \
				contact.o \
				mining-dialog.o \
				transaction-manager.o \
				transaction-view.o \
				connections.o \
				daemon.o

BASE_OBJ 	  = transaction.o \
				node.o \
				block.o \
				blockchain.o \
				receipt.o \
				merkle-helpers.o \
				rsa-fs.o \
				dat-fs.o \
				transmitter.o \
				shared-mem.o \
				parse-json.o \
				validation.o \
				hashing.o \
				dssize.o \
				utility.o \
				rsautil.o \

MOC = 		moc_mainwindow.cpp \
			moc_transactionlist.cpp \
			moc_mining_status.cpp \
			moc_firebase_auth.cpp \
			moc_account_pages.cpp

DIST = 		/usr/lib/qt/mkspecs/features/spec_pre.prf \
			/usr/lib/qt/mkspecs/common/unix.conf \
			/usr/lib/qt/mkspecs/common/linux.conf \
			/usr/lib/qt/mkspecs/common/sanitize.conf \
			/usr/lib/qt/mkspecs/common/gcc-base.conf \
			/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
			/usr/lib/qt/mkspecs/common/clang.conf \
			/usr/lib/qt/mkspecs/qconfig.pri \
			/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
			/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
			/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
			/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
			/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
			/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
			/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
			/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
			/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
			/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
			/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
			/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
			/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
			/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
			/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
			/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
			/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
			/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
			/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
			/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
			/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
			/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
			/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
			/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
			/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
			/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
			/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
			/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
			/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
			/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
			/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
			/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
			/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
			/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
			/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
			/usr/lib/qt/mkspecs/modules/qt_KService.pri \
			/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
			/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
			/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
			/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
			/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
			/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
			/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
			/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
			/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3d.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
			/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
			/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
			/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
			/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
			/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
			/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
			/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
			/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
			/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
			/usr/lib/qt/mkspecs/features/qt_functions.prf \
			/usr/lib/qt/mkspecs/features/qt_config.prf \
			/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
			/usr/lib/qt/mkspecs/features/spec_post.prf \
			../plasmacoin-client/.qmake.stash \
			/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
			/usr/lib/qt/mkspecs/features/toolchain.prf \
			/usr/lib/qt/mkspecs/features/default_pre.prf \
			/usr/lib/qt/mkspecs/features/resolve_config.prf \
			/usr/lib/qt/mkspecs/features/default_post.prf \
			/usr/lib/qt/mkspecs/features/qml_debug.prf \
			/usr/lib/qt/mkspecs/features/warn_on.prf \
			/usr/lib/qt/mkspecs/features/qt.prf \
			/usr/lib/qt/mkspecs/features/resources_functions.prf \
			/usr/lib/qt/mkspecs/features/resources.prf \
			/usr/lib/qt/mkspecs/features/moc.prf \
			/usr/lib/qt/mkspecs/features/unix/opengl.prf \
			/usr/lib/qt/mkspecs/features/uic.prf \
			/usr/lib/qt/mkspecs/features/unix/thread.prf \
			/usr/lib/qt/mkspecs/features/qmake_use.prf \
			/usr/lib/qt/mkspecs/features/file_copies.prf \
			/usr/lib/qt/mkspecs/features/testcase_targets.prf \
			/usr/lib/qt/mkspecs/features/exceptions.prf \
			/usr/lib/qt/mkspecs/features/yacc.prf \
			/usr/lib/qt/mkspecs/features/lex.prf \
			cryptopp-sha256-libs.h \
			../../transaction.hpp ../../transaction.cpp \
			../../node.hpp ../../node.cpp \
			../../block.hpp ../../block.hpp \
			../../blockchain.hpp ../../blockchain.cpp \
			../../receipt.hpp ../../receipt.cpp \
			../../merkle-helpers.h ../../merkle-helpers.c \
			../../rsa-fs.hpp ../../rsa-fs.cpp \
			../../dat-fs.hpp ../../dat-fs.cpp \
			../../transmitter.hpp ../../transmitter.cpp \
			../../shared-mem.hpp ../../shared-mem.cpp \
			../../parse-json.hpp ../../parse-json.cpp \
			../../validation.hpp ../../validation.cpp \
			../../hashing.hpp ../../hashing.cpp \
			../../dssize.hpp ../../dssize.cpp \
			../../utility.hpp ../../utility.cpp \
			../../rsautil.hpp ../../rsautil.cpp \
			../plasmacoin-client/plasmacoin-client.pro ../plasmacoin-client/main.cpp \
			../plasmacoin-client/mainwindow.h ../plasmacoin-client/mainwindow.cpp \
			../plasmacoin-client/transaction-list.h ../plasmacoin-client/transaction-list.cpp \
			../plasmacoin-client/mining-status.h ../plasmacoin-client/mining-status.cpp \
			../plasmacoin-client/recipient-list.h ../plasmacoin-client/recipient-list.cpp \
			../plasmacoin-client/firebase-auth.h ../plasmacoin-client/firebase-auth.cpp \
			../plasmacoin-client/account-pages.h ../plasmacoin-client/account-pages.cpp \
			../plasmacoin-client/address-book.h ../plasmacoin-client/address-book.cpp \
			../plasmacoin-client/contact.h ../plasmacoin-client/contact.cpp \
			../plasmacoin-client/mining-dialog.h ../plasmacoin-client/mining-dialog.cpp \
			../plasmacoin-client/transaction-manager.h ../plasmacoin-client/transaction-manager.cpp \
			../plasmacoin-client/transaction-view.h ../plasmacoin-client/transaction-view.cpp \
			../plasmacoin-client/connections.hpp ../plasmacoin-client/connections.cpp \
			\
			../../../daemon/goexports.go ../../../daemon/pcnetworkd.h ../../../daemon/daemon.cpp \
			../../../handler/handler.go \
			../../../netutils/compression.go ../../../netutils/netutils.go ../../../netutils/parser.go \
			../../../tcpnet/netdial.go ../../../tcpnet/netlisten.go

QMAKE_TARGET  = plasmacoin-client
DESTDIR       =
TARGET        = plasmacoin-client


first: all
####### Build rules

plasmacoin-client: ui_mainwindow.h $(OBJECTS)
	$(eval CLIENT_OBJS := $(filter-out daemon.o, $(OBJECTS)))
	$(LINK) $(LFLAGS) -o $(TARGET) $(CLIENT_OBJS) $(OBJCOMP) $(LIBS)

pcnetworkd: daemon.o
	$(LINK) $(LFLAGS) -o pcnetworkd daemon.o $(OBJCOMP) $(DAEMON_LIBS) $(QTLIBS)

Makefile: ../plasmacoin-client/plasmacoin-client.pro /usr/lib/qt/mkspecs/linux-clang/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/clang.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-clang/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		../plasmacoin-client/plasmacoin-client.pro
	$(QMAKE) -o QMakefile.mk ../plasmacoin-client/plasmacoin-client.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/clang.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KUserFeedbackWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_Qt5Keychain.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-clang/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/qml_debug.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
../plasmacoin-client/plasmacoin-client.pro:
qmake: FORCE
	@$(QMAKE) -o QMakefile.mk ../plasmacoin-client/plasmacoin-client.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

all: Makefile libpcnetworkd.so libplasmacoin.so pcnetworkd plasmacoin-client

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../plasmacoin-client/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../plasmacoin-client/main.cpp ../plasmacoin-client/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../plasmacoin-client/ui/linux.ui $(DISTDIR)/


clean: compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) ../../../daemon/pcnetworkd.h
	-$(DEL_DIR) ../../../lib


distclean: clean
	-$(DEL_FILE) $(TARGET)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: $(MOC)
compiler_moc_header_clean:
	-$(DEL_FILE) $(MOC)

moc_mainwindow.cpp: ../plasmacoin-client/mainwindow.h \
		ui_mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I./plasmacoin-client -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/aarch64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/local/include -I/usr/lib/clang/11.1.0/include -I/usr/include -I$(CRYPTOPP) ../plasmacoin-client/mainwindow.h -o moc_mainwindow.cpp

moc_transactionlist.cpp: ../plasmacoin-client/transaction-list.h \
		ui_mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I../plasmacoin-client -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/aarch64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/local/include -I/usr/lib/clang/11.1.0/include -I/usr/include -I$(CRYPTOPP) ../plasmacoin-client/transaction-list.h -o moc_transactionlist.cpp

moc_mining_status.cpp: ../plasmacoin-client/mining-status.h \
		ui_mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I../plasmacoin-client -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/aarch64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/local/include -I/usr/lib/clang/11.1.0/include -I/usr/include -I$(CRYPTOPP) ../plasmacoin-client/mining-status.h -o moc_mining_status.cpp

moc_firebase_auth.cpp: ../plasmacoin-client/ \
		ui_mainwindow.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I../plasmacoin-client -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/aarch64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/local/include -I/usr/lib/clang/11.1.0/include -I/usr/include -I$(CRYPTOPP) ../plasmacoin-client/firebase-auth.h -o moc_firebase_auth.cpp

moc_mining_dialog.cpp: ../plasmacoin-client/ \
		ui_miningdialog.h \
		/opt/homebrew/share/qt/libexec/moc
	/opt/homebrew/share/qt/libexec/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-clang -I../plasmacoin-client -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/aarch64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/local/include -I/usr/lib/clang/11.1.0/include -I/usr/include -I/usr/src/cryptopp ../plasmacoin-client/mining-dialog.h -o moc_mining_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_miningdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_miningdialog.h
ui_mainwindow.h: ../plasmacoin-client/ui/linux.ui \
				 /usr/bin/uic
	/usr/bin/uic ../plasmacoin-client/ui/linux.ui -o ui_mainwindow.h

ui_miningdialog.h: ../plasmacoin-client/ui/miningdialog.ui /opt/homebrew/share/qt/libexec/uic
	/opt/homebrew/share/qt/libexec/uic ../plasmacoin-client/ui/miningdialog.ui -o ui_miningdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean

####### Compile

# Blockchain

transaction.o: ../../transaction.cpp ../../transaction.hpp ../../receipt.hpp ../../utility.hpp \
			   ../../signature.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transaction.o ../../transaction.cpp

node.o: ../../node.cpp ../../node.hpp ../../cryptopp-sha256-libs.h ../../transaction.hpp \
		../../block.hpp ../../blockchain.hpp ../../rsa-fs.hpp ../../dat-fs.hpp ../../packet-types.h \
		../../transmitter.hpp ../../shared-mem.hpp ../../parse-json.hpp ../../utility.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o ../../node.cpp

block.o: ../../block.cpp ../../block.hpp ../../transaction.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o ../../block.cpp

blockchain.o: ../../blockchain.cpp ../../blockchain.hpp ../../cryptopp-sha256-libs.h ../../block.hpp \
			  ../../merkle-helpers.h ../../../daemon/pcnetworkd.h ../../packet-types.h ../../shared-mem.hpp \
			  ../../parse-json.hpp ../../validation.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blockchain.o ../../blockchain.cpp

receipt.o: ../../receipt.cpp ../../receipt.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o receipt.o ../../receipt.cpp

merkle-helpers.o: ../../merkle-helpers.c ../../merkle-helpers.h
	$(CXX) -c $(CFLAGS) $(INCPATH) -o merkle-helpers.o ../../merkle-helpers.c

rsa-fs.o: ../../rsa-fs.cpp ../../rsa-fs.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsa-fs.o ../../rsa-fs.cpp

dat-fs.o: ../../dat-fs.cpp ../../dat-fs.hpp ../../block.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dat-fs.o ../../dat-fs.cpp

transmitter.o: ../../transmitter.cpp ../../transmitter.hpp ../../../daemon/pcnetworkd.h \
			   ../../transaction.hpp ../../node.hpp ../../block.hpp ../../packet-types.h \
			   ../../receipt.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transmitter.o ../../transmitter.cpp

shared-mem.o: ../../shared-mem.cpp ../../shared-mem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shared-mem.o ../../shared-mem.cpp

parse-json.o: ../../parse-json.cpp ../../parse-json.hpp ../../block.hpp ../../packet-types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parse-json.o ../../parse-json.cpp

validation.o: ../../validation.cpp ../../validation.hpp ../../blockchain.hpp ../../transaction.hpp \
			  ../../block.hpp ../../hashing.hpp ../../rsautil.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validation.o ../../validation.cpp

hashing.o: ../../hashing.cpp ../../hashing.hpp ../../transaction.hpp ../../block.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hashing.o ../../hashing.cpp

dssize.o: ../../dssize.cpp ../../dssize.hpp ../../transaction.hpp ../../block.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dssize.o ../../dssize.cpp

utility.o: ../../utility.cpp ../../utility.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utility.o ../../utility.cpp

rsautil.o: ../../rsautil.cpp ../../rsautil.hpp ../../transaction.hpp ../../receipt.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsautil.o ../../rsautil.cpp

# GUI

main.o: ../plasmacoin-client/main.cpp ../plasmacoin-client/mainwindow.h \
		ui_mainwindow.h ui_miningdialog.h ../plasmacoin-client/connections.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../plasmacoin-client/main.cpp

mainwindow.o: ../plasmacoin-client/mainwindow.cpp ../plasmacoin-client/mainwindow.h \
			  ../plasmacoin-client/transaction-list.h ../plasmacoin-client/account-pages.h \
			  ../plasmacoin-client/firebase-auth.h ../plasmacoin-client/address-book.h \
			  ../plasmacoin-client/contact.h ../../shared-mem.hpp ../plasmacoin-client/transaction-view.h \
			  ../plasmacoin-client/transaction-manager.h ../../rsa-fs.hpp ../plasmacoin-client/firebase-auth.h \
			  ../../validation.hpp ../../dssize.hpp ui_mainwindow.h ui_miningdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../plasmacoin-client/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mining_status.o: moc_mining_status.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mining_status.o moc_mining_status.cpp

moc_firebase_auth.o: moc_firebase_auth.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_firebase_auth.o moc_firebase_auth.cpp

moc_account_pages.o: moc_account_pages.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_account_pages.o moc_account_pages.cpp

transaction-list.o: ../plasmacoin-client/transaction-list.cpp ../plasmacoin-client/transaction-list.h \
					ui_mainwindow.h ../../transaction.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transaction-list.o ../plasmacoin-client/transaction-list.cpp

mining-status.o: ../plasmacoin-client/mining-status.cpp ../plasmacoin-client/mining-status.h \
				 ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mining-status.o ../plasmacoin-client/mining-status.cpp

firebase-auth.o: ../plasmacoin-client/firebase-auth.cpp ../plasmacoin-client/firebase-auth.h \
				 ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o firebase-auth.o ../plasmacoin-client/firebase-auth.cpp

account-pages.o: ../plasmacoin-client/account-pages.cpp ../plasmacoin-client/account-pages.h \
				 ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account-pages.o ../plasmacoin-client/account-pages.cpp

address-book.o: ../plasmacoin-client/address-book.cpp ../plasmacoin-client/address-book.h \
				ui_mainwindow.h ../plasmacoin-client/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o address-book.o ../plasmacoin-client/address-book.cpp

contact.o: ../plasmacoin-client/contact.cpp ../plasmacoin-client/contact.h ui_miningdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o ../plasmacoin-client/contact.cpp

mining-dialog.o: ../plasmacoin-client/mining-dialog.cpp ../plasmacoin-client/mining-dialog.h \
				 ../../block.hpp ../../dssize.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mining-dialog.o ../plasmacoin-client/mining-dialog.cpp

transaction-manager.o: ../plasmacoin-client/transaction-manager.cpp ../plasmacoin-client/transaction-manager.h \
					   ui_mainwindow.h ../plasmacoin-client/address-book.h ../plasmacoin-client/contact.h \
					   ../../transaction.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transaction-manager.o ../plasmacoin-client/transaction-manager.cpp

transaction-view.o: ../plasmacoin-client/transaction-view.cpp ../plasmacoin-client/transaction-view.h \
					ui_mainwindow.h ../../transaction.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transaction-view.o ../plasmacoin-client/transaction-view.cpp

connections.o: ../plasmacoin-client/connections.cpp ../plasmacoin-client/connections.hpp \
			   ../plasmacoin-client/mainwindow.h ui_mainwindow.h ../plasmacoin-client/firebase-auth.h \
			   ../../transmitter.hpp ../../shared-mem.hpp ../../packet-types.h ../../parse-json.hpp \
			   ../../dssize.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connections.o ../plasmacoin-client/connections.cpp

# settings-manager.o: ../plasmacoin-client/settings-manager.cpp ../plasmacoin-client/settings-manager.h \
# 					ui_mainwindow.h
# 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings-manager.o ../plasmacoin-client/settings-manager.cpp

# Network Daemon

daemon.o: ../../../daemon/daemon.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o daemon.o ../../../daemon/daemon.cpp

# settings-manager.o: ../plasmacoin-client/settings-manager.cpp ../plasmacoin-client/settings-manager.h \
# 					ui_mainwindow.h
# 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings-manager.o ../plasmacoin-client/settings-manager.cpp

# Shared Objects

# Compile the Go code into a C header
libpcnetworkd.so: ../../../daemon/pcnetworkd.go
	$(MKDIR) ../../../lib $(LIBPLASMACOIN)
	$(GO) build $(GOFLAGS) -o ../../../daemon/libpcnetworkd.so ../../../daemon/pcnetworkd.go
	$(MOVE) ../../../daemon/libpcnetworkd.h ../../../daemon/pcnetworkd.h
	$(MOVE) ../../../daemon/libpcnetworkd.so ../../../lib
	$(INSTALL_FILE) ../../../lib/libpcnetworkd.so $(LIBPLASMACOIN)

# Compile Plasmacoin base libraries into a shared object and make the necessary headers
# publicly accessible across the system.
libplasmacoin.so: $(BASE_OBJ)
	$(MKDIR) $(HEADER_DIR)
	$(CXX) -shared $(BASE_OBJ) -L/usr/src/cryptopp -L/usr/lib/ -L/usr/lib/qt -L/usr/lib/plasmacoin -o ../../../lib/libplasmacoin.so /usr/src/cryptopp/libcryptopp.a /usr/lib/plasmacoin/libpcnetworkd.so /usr/lib/libboost_system.so $(QTLIBS)
	$(INSTALL_FILE) ../../../lib/libplasmacoin.so $(LIBPLASMACOIN)

	$(eval STANDALONE_HEADERS = ../../merkle-helpers.h ../../cryptopp-sha256-libs.h ../../../daemon/pcnetworkd.h)
	$(eval HEADERS := $(filter-out merkle-helpers.o, $(BASE_OBJ)))
	$(eval HEADERS := $(HEADERS:%o=../../%hpp))
	$(eval HEADERS += $(STANDALONE_HEADERS))

	$(COPY_FILE) $(HEADERS) $(HEADER_DIR)

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/plasmacoin-client/bin || mkdir -p $(INSTALL_ROOT)/opt/plasmacoin-client/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/plasmacoin-client/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/plasmacoin-client/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/plasmacoin-client/bin/


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:
